/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/404': RouteRecordInfo<
      '/404',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/': RouteRecordInfo<
      '/about/',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/site': RouteRecordInfo<
      '/about/site',
      '/about/site',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/air-conditioner/': RouteRecordInfo<
      '/air-conditioner/',
      '/air-conditioner',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/albums/': RouteRecordInfo<
      '/albums/',
      '/albums',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/archives/': RouteRecordInfo<
      '/archives/',
      '/archives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories/': RouteRecordInfo<
      '/categories/',
      '/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/crypto/': RouteRecordInfo<
      '/crypto/',
      '/crypto',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/games/': RouteRecordInfo<
      '/games/',
      '/games',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/links/': RouteRecordInfo<
      '/links/',
      '/links',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/page/[page]': RouteRecordInfo<
      '/page/[page]',
      '/page/:page',
      { page: ParamValue<true> },
      { page: ParamValue<false> },
      | never
    >,
    '/posts/': RouteRecordInfo<
      '/posts/',
      '/posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/《八仙》观后感': RouteRecordInfo<
      '/posts/《八仙》观后感',
      '/posts/%E3%80%8A%E5%85%AB%E4%BB%99%E3%80%8B%E8%A7%82%E5%90%8E%E6%84%9F',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/博客上线啦！博客诞生的心路历程': RouteRecordInfo<
      '/posts/博客上线啦！博客诞生的心路历程',
      '/posts/%E5%8D%9A%E5%AE%A2%E4%B8%8A%E7%BA%BF%E5%95%A6%EF%BC%81%E5%8D%9A%E5%AE%A2%E8%AF%9E%E7%94%9F%E7%9A%84%E5%BF%83%E8%B7%AF%E5%8E%86%E7%A8%8B',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/博客部署到CloudFlare和Github': RouteRecordInfo<
      '/posts/博客部署到CloudFlare和Github',
      '/posts/%E5%8D%9A%E5%AE%A2%E9%83%A8%E7%BD%B2%E5%88%B0CloudFlare%E5%92%8CGithub',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/博客魔改记录': RouteRecordInfo<
      '/posts/博客魔改记录',
      '/posts/%E5%8D%9A%E5%AE%A2%E9%AD%94%E6%94%B9%E8%AE%B0%E5%BD%95',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/大模型学习(1)': RouteRecordInfo<
      '/posts/大模型学习(1)',
      '/posts/%E5%A4%A7%E6%A8%A1%E5%9E%8B%E5%AD%A6%E4%B9%A0(1)',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/安知鱼主题接入51LA统计展示访问数据': RouteRecordInfo<
      '/posts/安知鱼主题接入51LA统计展示访问数据',
      '/posts/%E5%AE%89%E7%9F%A5%E9%B1%BC%E4%B8%BB%E9%A2%98%E6%8E%A5%E5%85%A551LA%E7%BB%9F%E8%AE%A1%E5%B1%95%E7%A4%BA%E8%AE%BF%E9%97%AE%E6%95%B0%E6%8D%AE',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/安知鱼主题接入DeepSeek实现AI摘要': RouteRecordInfo<
      '/posts/安知鱼主题接入DeepSeek实现AI摘要',
      '/posts/%E5%AE%89%E7%9F%A5%E9%B1%BC%E4%B8%BB%E9%A2%98%E6%8E%A5%E5%85%A5DeepSeek%E5%AE%9E%E7%8E%B0AI%E6%91%98%E8%A6%81',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/安知鱼接入腾讯位置服务实现访客IP定位': RouteRecordInfo<
      '/posts/安知鱼接入腾讯位置服务实现访客IP定位',
      '/posts/%E5%AE%89%E7%9F%A5%E9%B1%BC%E6%8E%A5%E5%85%A5%E8%85%BE%E8%AE%AF%E4%BD%8D%E7%BD%AE%E6%9C%8D%E5%8A%A1%E5%AE%9E%E7%8E%B0%E8%AE%BF%E5%AE%A2IP%E5%AE%9A%E4%BD%8D',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/文字修仙游戏上线啦': RouteRecordInfo<
      '/posts/文字修仙游戏上线啦',
      '/posts/%E6%96%87%E5%AD%97%E4%BF%AE%E4%BB%99%E6%B8%B8%E6%88%8F%E4%B8%8A%E7%BA%BF%E5%95%A6',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/玩黑神话悟空有感': RouteRecordInfo<
      '/posts/玩黑神话悟空有感',
      '/posts/%E7%8E%A9%E9%BB%91%E7%A5%9E%E8%AF%9D%E6%82%9F%E7%A9%BA%E6%9C%89%E6%84%9F',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/给博客添加FPS监测': RouteRecordInfo<
      '/posts/给博客添加FPS监测',
      '/posts/%E7%BB%99%E5%8D%9A%E5%AE%A2%E6%B7%BB%E5%8A%A0FPS%E7%9B%91%E6%B5%8B',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/给博客装个小空调': RouteRecordInfo<
      '/posts/给博客装个小空调',
      '/posts/%E7%BB%99%E5%8D%9A%E5%AE%A2%E8%A3%85%E4%B8%AA%E5%B0%8F%E7%A9%BA%E8%B0%83',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/记录一下我的键盘': RouteRecordInfo<
      '/posts/记录一下我的键盘',
      '/posts/%E8%AE%B0%E5%BD%95%E4%B8%80%E4%B8%8B%E6%88%91%E7%9A%84%E9%94%AE%E7%9B%98',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/games开发文档': RouteRecordInfo<
      '/posts/games开发文档',
      '/posts/games%E5%BC%80%E5%8F%91%E6%96%87%E6%A1%A3',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/hello-valaxy': RouteRecordInfo<
      '/posts/hello-valaxy',
      '/posts/hello-valaxy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/MaixCamera学习笔记': RouteRecordInfo<
      '/posts/MaixCamera学习笔记',
      '/posts/MaixCamera%E5%AD%A6%E4%B9%A0%E7%AC%94%E8%AE%B0',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Markdown编辑器推荐': RouteRecordInfo<
      '/posts/Markdown编辑器推荐',
      '/posts/Markdown%E7%BC%96%E8%BE%91%E5%99%A8%E6%8E%A8%E8%8D%90',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/moments开发文档': RouteRecordInfo<
      '/posts/moments开发文档',
      '/posts/moments%E5%BC%80%E5%8F%91%E6%96%87%E6%A1%A3',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/TIFF图片格式详解': RouteRecordInfo<
      '/posts/TIFF图片格式详解',
      '/posts/TIFF%E5%9B%BE%E7%89%87%E6%A0%BC%E5%BC%8F%E8%AF%A6%E8%A7%A3',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Trae接入混元限时免费模型': RouteRecordInfo<
      '/posts/Trae接入混元限时免费模型',
      '/posts/Trae%E6%8E%A5%E5%85%A5%E6%B7%B7%E5%85%83%E9%99%90%E6%97%B6%E5%85%8D%E8%B4%B9%E6%A8%A1%E5%9E%8B',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Twikoo博主标识实现与QQ邮箱踩坑': RouteRecordInfo<
      '/posts/Twikoo博主标识实现与QQ邮箱踩坑',
      '/posts/Twikoo%E5%8D%9A%E4%B8%BB%E6%A0%87%E8%AF%86%E5%AE%9E%E7%8E%B0%E4%B8%8EQQ%E9%82%AE%E7%AE%B1%E8%B8%A9%E5%9D%91',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tags/': RouteRecordInfo<
      '/tags/',
      '/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/xiuxian/': RouteRecordInfo<
      '/xiuxian/',
      '/xiuxian',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'node_modules/.pnpm/valaxy-theme-yun@1.0.0-rc.3_ef2a315ab37cd12622daad85a3aa02da/node_modules/valaxy-theme-yun/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'node_modules/.pnpm/valaxy@1.0.0-rc.3_@babel+pa_beb57da21878ee70f09d1aed2fd9a891/node_modules/valaxy/client/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
      pathParamNames:
        | 'path'
    }
    'pages/404.md': {
      routes:
        | '/404'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/about/index.md': {
      routes:
        | '/about/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/about/site.md': {
      routes:
        | '/about/site'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/air-conditioner/index.md': {
      routes:
        | '/air-conditioner/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/albums/index.md': {
      routes:
        | '/albums/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/archives/index.md': {
      routes:
        | '/archives/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/categories/index.md': {
      routes:
        | '/categories/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/crypto/index.md': {
      routes:
        | '/crypto/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/games/index.md': {
      routes:
        | '/games/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/links/index.md': {
      routes:
        | '/links/'
      views:
        | never
      pathParamNames:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@1.0.0-rc.3_ef2a315ab37cd12622daad85a3aa02da/node_modules/valaxy-theme-yun/pages/page/[page].vue': {
      routes:
        | '/page/[page]'
      views:
        | never
      pathParamNames:
        | 'page'
    }
    'node_modules/.pnpm/valaxy-theme-yun@1.0.0-rc.3_ef2a315ab37cd12622daad85a3aa02da/node_modules/valaxy-theme-yun/pages/posts/index.vue': {
      routes:
        | '/posts/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/《八仙》观后感.md': {
      routes:
        | '/posts/《八仙》观后感'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/博客上线啦！博客诞生的心路历程.md': {
      routes:
        | '/posts/博客上线啦！博客诞生的心路历程'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/博客部署到CloudFlare和Github.md': {
      routes:
        | '/posts/博客部署到CloudFlare和Github'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/博客魔改记录.md': {
      routes:
        | '/posts/博客魔改记录'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/大模型学习(1).md': {
      routes:
        | '/posts/大模型学习(1)'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/安知鱼主题接入51LA统计展示访问数据.md': {
      routes:
        | '/posts/安知鱼主题接入51LA统计展示访问数据'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/安知鱼主题接入DeepSeek实现AI摘要.md': {
      routes:
        | '/posts/安知鱼主题接入DeepSeek实现AI摘要'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/安知鱼接入腾讯位置服务实现访客IP定位.md': {
      routes:
        | '/posts/安知鱼接入腾讯位置服务实现访客IP定位'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/文字修仙游戏上线啦.md': {
      routes:
        | '/posts/文字修仙游戏上线啦'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/玩黑神话悟空有感.md': {
      routes:
        | '/posts/玩黑神话悟空有感'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/给博客添加FPS监测.md': {
      routes:
        | '/posts/给博客添加FPS监测'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/给博客装个小空调.md': {
      routes:
        | '/posts/给博客装个小空调'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/记录一下我的键盘.md': {
      routes:
        | '/posts/记录一下我的键盘'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/games开发文档.md': {
      routes:
        | '/posts/games开发文档'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/hello-valaxy.md': {
      routes:
        | '/posts/hello-valaxy'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/MaixCamera学习笔记.md': {
      routes:
        | '/posts/MaixCamera学习笔记'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/Markdown编辑器推荐.md': {
      routes:
        | '/posts/Markdown编辑器推荐'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/moments开发文档.md': {
      routes:
        | '/posts/moments开发文档'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/TIFF图片格式详解.md': {
      routes:
        | '/posts/TIFF图片格式详解'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/Trae接入混元限时免费模型.md': {
      routes:
        | '/posts/Trae接入混元限时免费模型'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/Twikoo博主标识实现与QQ邮箱踩坑.md': {
      routes:
        | '/posts/Twikoo博主标识实现与QQ邮箱踩坑'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/tags/index.md': {
      routes:
        | '/tags/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/xiuxian/index.md': {
      routes:
        | '/xiuxian/'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
