/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/404': RouteRecordInfo<
      '/404',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/': RouteRecordInfo<
      '/about/',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/site': RouteRecordInfo<
      '/about/site',
      '/about/site',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/air-conditioner/': RouteRecordInfo<
      '/air-conditioner/',
      '/air-conditioner',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/albums/': RouteRecordInfo<
      '/albums/',
      '/albums',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/archives/': RouteRecordInfo<
      '/archives/',
      '/archives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories/': RouteRecordInfo<
      '/categories/',
      '/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/crypto/': RouteRecordInfo<
      '/crypto/',
      '/crypto',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/games/': RouteRecordInfo<
      '/games/',
      '/games',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/links/': RouteRecordInfo<
      '/links/',
      '/links',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/page/[page]': RouteRecordInfo<
      '/page/[page]',
      '/page/:page',
      { page: ParamValue<true> },
      { page: ParamValue<false> },
      | never
    >,
    '/posts/': RouteRecordInfo<
      '/posts/',
      '/posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2026-movie-list': RouteRecordInfo<
      '/posts/2026-movie-list',
      '/posts/2026-movie-list',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/anzhiyu-51la-stats': RouteRecordInfo<
      '/posts/anzhiyu-51la-stats',
      '/posts/anzhiyu-51la-stats',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/anzhiyu-deepseek-ai-summary': RouteRecordInfo<
      '/posts/anzhiyu-deepseek-ai-summary',
      '/posts/anzhiyu-deepseek-ai-summary',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/anzhiyu-tencent-ip-location': RouteRecordInfo<
      '/posts/anzhiyu-tencent-ip-location',
      '/posts/anzhiyu-tencent-ip-location',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/baxian-review': RouteRecordInfo<
      '/posts/baxian-review',
      '/posts/baxian-review',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/blog-air-conditioner': RouteRecordInfo<
      '/posts/blog-air-conditioner',
      '/posts/blog-air-conditioner',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/blog-customization-log': RouteRecordInfo<
      '/posts/blog-customization-log',
      '/posts/blog-customization-log',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/blog-deploy-cloudflare-github': RouteRecordInfo<
      '/posts/blog-deploy-cloudflare-github',
      '/posts/blog-deploy-cloudflare-github',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/blog-fps-monitor': RouteRecordInfo<
      '/posts/blog-fps-monitor',
      '/posts/blog-fps-monitor',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/blog-launch-story': RouteRecordInfo<
      '/posts/blog-launch-story',
      '/posts/blog-launch-story',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/complete': RouteRecordInfo<
      '/posts/complete',
      '/posts/complete',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/games-dev-doc': RouteRecordInfo<
      '/posts/games-dev-doc',
      '/posts/games-dev-doc',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/hello-valaxy': RouteRecordInfo<
      '/posts/hello-valaxy',
      '/posts/hello-valaxy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/llm-learning-1': RouteRecordInfo<
      '/posts/llm-learning-1',
      '/posts/llm-learning-1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/llm-learning-2': RouteRecordInfo<
      '/posts/llm-learning-2',
      '/posts/llm-learning-2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/llm-learning-3': RouteRecordInfo<
      '/posts/llm-learning-3',
      '/posts/llm-learning-3',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/maixcamera-notes': RouteRecordInfo<
      '/posts/maixcamera-notes',
      '/posts/maixcamera-notes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/markdown-editor-recommendation': RouteRecordInfo<
      '/posts/markdown-editor-recommendation',
      '/posts/markdown-editor-recommendation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/moments-dev-doc': RouteRecordInfo<
      '/posts/moments-dev-doc',
      '/posts/moments-dev-doc',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/my-keyboard': RouteRecordInfo<
      '/posts/my-keyboard',
      '/posts/my-keyboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/saa-chatModel-and-chatClient': RouteRecordInfo<
      '/posts/saa-chatModel-and-chatClient',
      '/posts/saa-chatModel-and-chatClient',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/text-xiuxian-game': RouteRecordInfo<
      '/posts/text-xiuxian-game',
      '/posts/text-xiuxian-game',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/tiff-format': RouteRecordInfo<
      '/posts/tiff-format',
      '/posts/tiff-format',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/trae-hunyuan-free-model': RouteRecordInfo<
      '/posts/trae-hunyuan-free-model',
      '/posts/trae-hunyuan-free-model',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/twikoo-blogger-badge-qq-mail': RouteRecordInfo<
      '/posts/twikoo-blogger-badge-qq-mail',
      '/posts/twikoo-blogger-badge-qq-mail',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/wukong-review': RouteRecordInfo<
      '/posts/wukong-review',
      '/posts/wukong-review',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tags/': RouteRecordInfo<
      '/tags/',
      '/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/xiuxian/': RouteRecordInfo<
      '/xiuxian/',
      '/xiuxian',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'node_modules/.pnpm/valaxy-theme-yun@1.0.0-rc.3_ef2a315ab37cd12622daad85a3aa02da/node_modules/valaxy-theme-yun/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'node_modules/.pnpm/valaxy@1.0.0-rc.3_@babel+pa_beb57da21878ee70f09d1aed2fd9a891/node_modules/valaxy/client/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
      pathParamNames:
        | 'path'
    }
    'pages/404.md': {
      routes:
        | '/404'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/about/index.md': {
      routes:
        | '/about/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/about/site.md': {
      routes:
        | '/about/site'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/air-conditioner/index.vue': {
      routes:
        | '/air-conditioner/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/albums/index.vue': {
      routes:
        | '/albums/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/archives/index.md': {
      routes:
        | '/archives/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/categories/index.md': {
      routes:
        | '/categories/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/crypto/index.vue': {
      routes:
        | '/crypto/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/games/index.vue': {
      routes:
        | '/games/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/links/index.md': {
      routes:
        | '/links/'
      views:
        | never
      pathParamNames:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@1.0.0-rc.3_ef2a315ab37cd12622daad85a3aa02da/node_modules/valaxy-theme-yun/pages/page/[page].vue': {
      routes:
        | '/page/[page]'
      views:
        | never
      pathParamNames:
        | 'page'
    }
    'node_modules/.pnpm/valaxy-theme-yun@1.0.0-rc.3_ef2a315ab37cd12622daad85a3aa02da/node_modules/valaxy-theme-yun/pages/posts/index.vue': {
      routes:
        | '/posts/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/2026-movie-list.md': {
      routes:
        | '/posts/2026-movie-list'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/anzhiyu-51la-stats.md': {
      routes:
        | '/posts/anzhiyu-51la-stats'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/anzhiyu-deepseek-ai-summary.md': {
      routes:
        | '/posts/anzhiyu-deepseek-ai-summary'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/anzhiyu-tencent-ip-location.md': {
      routes:
        | '/posts/anzhiyu-tencent-ip-location'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/baxian-review.md': {
      routes:
        | '/posts/baxian-review'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/blog-air-conditioner.md': {
      routes:
        | '/posts/blog-air-conditioner'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/blog-customization-log.md': {
      routes:
        | '/posts/blog-customization-log'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/blog-deploy-cloudflare-github.md': {
      routes:
        | '/posts/blog-deploy-cloudflare-github'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/blog-fps-monitor.md': {
      routes:
        | '/posts/blog-fps-monitor'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/blog-launch-story.md': {
      routes:
        | '/posts/blog-launch-story'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/complete.md': {
      routes:
        | '/posts/complete'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/games-dev-doc.md': {
      routes:
        | '/posts/games-dev-doc'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/hello-valaxy.md': {
      routes:
        | '/posts/hello-valaxy'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/llm-learning-1.md': {
      routes:
        | '/posts/llm-learning-1'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/llm-learning-2.md': {
      routes:
        | '/posts/llm-learning-2'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/llm-learning-3.md': {
      routes:
        | '/posts/llm-learning-3'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/maixcamera-notes.md': {
      routes:
        | '/posts/maixcamera-notes'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/markdown-editor-recommendation.md': {
      routes:
        | '/posts/markdown-editor-recommendation'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/moments-dev-doc.md': {
      routes:
        | '/posts/moments-dev-doc'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/my-keyboard.md': {
      routes:
        | '/posts/my-keyboard'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/saa-chatModel-and-chatClient.md': {
      routes:
        | '/posts/saa-chatModel-and-chatClient'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/text-xiuxian-game.md': {
      routes:
        | '/posts/text-xiuxian-game'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/tiff-format.md': {
      routes:
        | '/posts/tiff-format'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/trae-hunyuan-free-model.md': {
      routes:
        | '/posts/trae-hunyuan-free-model'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/twikoo-blogger-badge-qq-mail.md': {
      routes:
        | '/posts/twikoo-blogger-badge-qq-mail'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/wukong-review.md': {
      routes:
        | '/posts/wukong-review'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/tags/index.md': {
      routes:
        | '/tags/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/xiuxian/index.md': {
      routes:
        | '/xiuxian/'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
